### ISSUE TITLE
Agregar un README

### ISSUE THREAD

**Issue by schomatis** [adrian-mb/intro-seguridad#3]
Más que nada para darle una introducción al repo, algo corto con link a los distintos archivos y qué son. Por ejemplo "Soluciones a los ABOs(link) utilizando la herramienta GDB(link al resumen-gdb) en arquitectura x86_64(link a resumen-x64). Los ejercicios analizados son: bullets con los distintos abos".

**Comment by adrian-mb** [comment]
Listo, ya lo agregué! Cualquier cosa decime.
Gracias y saludos!

**Comment by schomatis** [comment]
Perfecto!
